SENDGRID_API_KEY="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"
SERPAPI_API_KEY="9bb735b0c6a29e05efeb8051b860bd273dd2b14ec909edcb6b7e13def5c4ade8"
Email_ID="jasnajayaraj177@gmail.com"
OPENAI_API_KEY="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"
GOOGLE_API_KEY="AIzaSyB6bqm5aTxj7wTfk3K7T5jjmTouyFuq6fQ"
