SENDGRID_API_KEY = "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"
SERPAPI_API_KEY="e30548c008fe33f08112948b1a9c753e672c9bfe26ffd36574db96f0e24a74e1"
Email_ID = "jasnajayaraj177@gmail.com"
# Add your OpenAI API key here (do NOT commit real keys to public repos)
OPENAI_API_KEY = "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"
GOOGLE_API_KEY="AIzaSyDTzUAlwuelvpMCdRROouYV7_WMubVpUaQ"
